---
title: "Assignment 4"
format: html
editor: visual
---

# Data Preparation

General questions for office hours: Should we be doing all of our coding in the index.qmd file, or in a separate file?

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(ggrepel)
library(janitor)
library(sf)
library(tigris)

inadmissibles_2014 <- read_excel("cy_2014_ofo_inadmissibles_redacted.xlsx")

inadmissibles_2014 <-
  clean_names(inadmissibles_2014) |>
  filter(is.na(duplicate_subject_indicator)) |>
  mutate(event_created_datetime = ymd_hms(event_created_datetime)) |>
  mutate(month = month(event_created_datetime)) |>
  mutate(month_name = month(event_created_datetime, label = TRUE, abbr = FALSE))

glimpse(inadmissibles_2014)

```

# Graph 1

```{r}

inadmissibles_2014 |>
  count(citizenship_country_name) |>
  arrange(desc(n)) |>
  mutate(country_rank = row_number()) |>
  right_join(inadmissibles_2014, by = "citizenship_country_name") |>
  filter(country_rank <= 10) |>
  group_by(citizenship_country_name, mode_of_transport) |>
  mutate(crossings = n()) |>
  ungroup() |>
  ggplot(mapping=aes(x = fct_infreq(citizenship_country_name), y = mode_of_transport)) +
  geom_count(mapping = aes(size = crossings, color = mode_of_transport)) +
  geom_text(mapping = aes(label = crossings), vjust = -2.6, check_overlap = TRUE) +
  scale_size_area(max_size = 15) + 
  theme(axis.text.x = element_text(angle = 45, vjust = .85)) + 
  labs(x = "Country", y = "Mode of Transport", color = "Mode of Transport", size = "Number of Crossings", title = "Counts of Unauthorized Border Crossings by Country of Origin and\nMode of Transport")

```

# Graph 2

```{r}
inadmissibles_2014 |>
  count(citizenship_country_name) |>
  arrange(desc(n)) |>
  mutate(country_rank = row_number()) |>
  right_join(inadmissibles_2014, by = "citizenship_country_name") |>
  filter(country_rank <= 10, !is.na(age_at_event_creation_time)) |>
  ggplot() +
  geom_boxplot(mapping = aes(x = fct_infreq(citizenship_country_name), y = age_at_event_creation_time)) +
  labs(x = "Country of origin", y = "Age", title = "Age distributions by country of origin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .85))

```

# Graph 3

```{r}
#| fig-width: 10

inadmissibles_2014 |>
  count(citizenship_country_name) |>
  arrange(desc(n)) |>
  mutate(country_rank = row_number()) |>
  right_join(inadmissibles_2014, by = "citizenship_country_name") |>
  filter(country_rank <= 5, month != "NA") |>
  group_by(month, citizenship_country_name, mode_of_transport) |>
  mutate(crossings = n()) |>
  ungroup() |>
  ggplot(mapping = aes(x = month, y = crossings, color = fct_infreq(citizenship_country_name), group = citizenship_country_name)) +
  geom_line() +
  geom_point(mapping = aes(shape = fct_infreq(citizenship_country_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(0, 12, by=1)) +
  facet_wrap(~mode_of_transport) +
  labs(x = "Month", y = "Number of Crossings", title = "Unauthorized Border Crossings by Month, Country, and Mode of Transport", color = "Country of Origin", shape = "Country of Origin")

```

# Graph 4

```{r}

urban_areas <- urban_areas(cb = TRUE, year = 2014) 

top_cities <- urban_areas |>
  filter(NAME10 %in% c("Laredo, TX", "San Diego, CA", "Miami, FL", "New Orleans, LA", "San Francisco--Oakland, CA")) |>
  mutate(NAME10 = replace(NAME10, NAME10 == "San Francisco--Oakland, CA", "San Francisco, CA"))

top_cities <- top_cities |>
  rename(field_office_name = NAME10)
  
states <- tigris::states(cb = TRUE, progress_bar = FALSE) |>
  filter(!STATEFP %in% c("78", "69", "66", "60", "72", "02", "15"))

n <- inadmissibles_2014 |>
  count(field_office_name) |>
  arrange(desc(n)) |>
  filter(field_office_name %in% c("LAREDO", "SAN DIEGO", "MIAMI", "NEW ORLEANS", "SAN FRANCISCO")) |>
  mutate(field_office_name = case_when(field_office_name == "LAREDO" ~ "Laredo, TX",
                   field_office_name == "SAN DIEGO" ~ "San Diego, CA", 
                   field_office_name == "MIAMI" ~ "Miami, FL",
                   field_office_name == "NEW ORLEANS" ~ "New Orleans, LA",
                   field_office_name == "SAN FRANCISCO" ~ "San Francisco, CA"))

join <- left_join(x = top_cities, y = n, by = "field_office_name")

laredo <- st_point_on_surface(x = join) |>
  filter(field_office_name == "Laredo, TX")

miami <- st_point_on_surface(x = join) |>
  filter(field_office_name == "Miami, FL")

new_orleans <- st_point_on_surface(x = join) |>
  filter(field_office_name == "New Orleans, LA")

san_diego <- st_point_on_surface(x = join) |>
  filter(field_office_name == "San Diego, CA")

san_francisco <- st_point_on_surface(x = join) |>
  filter(field_office_name == "San Francisco, CA")

ggplot() + 
  geom_sf(data = states, fill = NA) + 
  geom_sf(data = laredo, color = "blue", size = 10) + 
  geom_sf_text(data = laredo, aes(label = field_office_name,),
               nudge_y = 2.0) +
  geom_sf_text(data = laredo, aes(label = n),
               nudge_y = -2.0) +
  geom_sf(data = san_diego, color = "green", size = 8) +
  geom_sf_text(data = san_diego, aes(label = field_office_name),
               nudge_y = 2.0) +
  geom_sf_text(data = san_diego, aes(label = n),
               nudge_y = -2.0) +
  geom_sf(data = san_francisco, color = "red", size = 2) +
  geom_sf_text(data = san_francisco, aes(label = field_office_name),
               nudge_y = 1.5, nudge_x = 1.5) +
  geom_sf_text(data = san_francisco, aes(label = n),
               nudge_y = -2.0) +
  geom_sf(data = new_orleans, color = "orange", size = 4) +
  geom_sf_text(data = new_orleans, aes(label = field_office_name),
               nudge_y = 1.5) +
  geom_sf_text(data = new_orleans, aes(label = n),
               nudge_y = -2.0) +
  geom_sf(data = miami, color = "pink", size = 6) +
  geom_sf_text(data = miami, aes(label = field_office_name),
               nudge_y = 1.5) +
  geom_sf_text(data = miami, aes(label = n),
               nudge_y = -2.0) +
  theme_void()
```
